.\" Manpage for WinRun
.\" Contact jmedved@jmedved.com to correct errors or typos.
.TH WINRUN 1 "CURR_DATE" "MAJOR.MINOR.PATCH" "WinRun Manual"


.SH NAME

WinRun \- Quick way to run programs in a similar way the Windows Run dialog does


.SH SYNOPSIS

.ad l
\fBwinrun\fP


.SH DESCRIPTION
Quick way to run programs in a similar way the Windows Run dialog does.


.SH AUTHOR

Josip Medved <jmedved@jmedved.com>
